# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f7d989411db2f527f26b1ddebc12a396a4d777a8d12eba542185f58e87e21a8b6f80c5d32b5b05fe3f2abd038f332860656acc4696bfd1b1ad26b4233ec1af1

test:
  secret_key_base: 3fa7644c8c6eb0a9c90b62f7f457b314566bb5141a45549ef662f350a870e759600826e98ebe7303dcffd832b97710b48ab69569139805a1eb34c4f8db39bdf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
